package Lecture_12.HomeWork;

public enum ConverterType {
    INCHESTOMETERS, METERSTOINCHES,
    FAHRENHEITSTOCELSIUS, CELSIUSTOFAHRENHEITS,
    KILOGRAMTOPOUND, POUNDROKILOGRAM,
    MILESTOKM, KMTOMILES

}
